import os
import psycopg
from psycopg.rows import tuple_row
from dotenv import load_dotenv

load_dotenv()


class DBRow(dict):
    """
    Allows database rows to work with both:
        row["username"]
    and:
        row[0]
    """

    def __init__(self, cursor, values):
        self._values = values
        columns = [column.name for column in cursor.description]
        super().__init__(zip(columns, values))

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


def hybrid_row(cursor):
    return DBRow(cursor, cursor._row)


class CompatibleCursor:
    """
    Keeps the existing ? placeholders in app.py working
    with PostgreSQL, which normally uses %s.
    """

    def __init__(self, cursor):
        self.cursor = cursor

    def execute(self, query, params=None):
        query = query.replace("?", "%s")
        return self.cursor.execute(query, params)

    def fetchone(self):
        row = self.cursor.fetchone()

        if row is None:
            return None

        return DBRow(self.cursor, row)

    def fetchall(self):
        rows = self.cursor.fetchall()

        return [
            DBRow(self.cursor, row)
            for row in rows
        ]


class CompatibleConnection:
    def __init__(self, connection):
        self.connection = connection

    def cursor(self):
        return CompatibleCursor(
            self.connection.cursor(row_factory=tuple_row)
        )

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


def get_connection():

    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is not configured."
        )

    connection = psycopg.connect(database_url)

    return CompatibleConnection(connection)


def create_table():

    conn = get_connection()
    cursor = conn.cursor()

    # Users table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        mobile TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        age INTEGER NOT NULL,
        username TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        profile_picture TEXT DEFAULT 'default.png'
    )
    """)

    # Admin table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS admin(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL
    )
    """)

    # Interview Results table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS interview_results(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT,
        interview_type TEXT,
        score TEXT,
        feedback TEXT,
        interview_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    from werkzeug.security import generate_password_hash

    cursor.execute("SELECT * FROM admin")

    if cursor.fetchone() is None:

        cursor.execute("""
        INSERT INTO admin(username,password)
        VALUES(%s,%s)
        """, (
            "admin",
            generate_password_hash("admin123")
        ))

    conn.commit()
    conn.close()


def save_result(username, interview_type, score, feedback):

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
    INSERT INTO interview_results
    (username, interview_type, score, feedback)
    VALUES (%s, %s, %s, %s)
    """, (
        username,
        interview_type,
        score,
        feedback
    ))

    conn.commit()
    conn.close()